version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - sed -i "s|_BACKEND_IP_|$Backend_ip|g" src/const/node-server-config.js
      - sed -i "s|_BUCKET_ADDRESS_|$Bucket_address|g" src/const/node-server-config.js
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://s3-pixelistic-frontend
#artifacts:
  #files:
    #- 'build/*'